FROM node:18-alpine as builder

WORKDIR /app

COPY ./apps/web/package*.json .


RUN npm install

COPY ./apps/web .

RUN npm run build

FROM nginx:alpine as production

RUN rm /etc/nginx/conf.d/default.conf

COPY ./docker/web/nginx.conf /etc/nginx/conf.d/

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]